# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

sys.path.append('eif/')
sys.path.append('abod/')
sys.path.append('hbos/')
sys.path.append('LOf/')
sys.path.append('FindCblof/')
sys.path.append('image/')
sys.path.append('PCA_/')

from eif.EIForest_UI import Ui_MainWindow_EIF
from eif.EIForestmodel_Test import Ui_MainWindow_EFmodel

from abod.FastABODModel_Test import Ui_MainWindow_model
from abod.FastABOD_UI import Ui_MainWindowv_FastABOD

from FindCblof.FindCBLOF_model_ui import Ui_MainWindowv_CBLOF_model
from FindCblof.FindCBLOF_ui import Ui_MainWindowv_FindCBLOF
from LOf.LOFModel_Test import Ui_MainWindowv_LOFmodel
from LOf.LOF_UI import Ui_MainWindowv_LOF
from hbos.hbos_test_ui import Ui_MainWindowv_test
from hbos.hbos_ui import Ui_MainWindowv_Hbos
from PCA_.pca_ui import *
from PCA_.pca_model_ui import Ui_MainWindowv_PCAmodel


class Ui_MainWindowv(object):
    def setupUi(self, MainWindowv):
        MainWindowv.setObjectName("MainWindowv")
        MainWindowv.setEnabled(True)
        MainWindowv.resize(800, 463)
        MainWindowv.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        MainWindowv.setFont(font)
        MainWindowv.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindowv.setAutoFillBackground(False)
        MainWindowv.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                  "color: rgb(13, 13, 13);")
        MainWindowv.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindowv)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(16, 16, 16);")
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(211, 255, 224);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 387))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_2.clicked.connect(self.goto_FindCBLOF)

        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.pushButton_5.clicked.connect(self.goto_HBOS)

        self.EIF_Model = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.EIF_Model.setObjectName("EIF_Model")
        self.gridLayout_3.addWidget(self.EIF_Model, 0, 1, 1, 1)
        self.EIF_Model.clicked.connect(self.goto_EIFmodel_test)

        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_3.clicked.connect(self.goto_FastABOD)

        self.pb_FindCBLOF_mode = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_FindCBLOF_mode.setObjectName("pb_FindCBLOF_mode")
        self.gridLayout_3.addWidget(self.pb_FindCBLOF_mode, 2, 1, 1, 1)
        self.pb_FindCBLOF_mode.clicked.connect(self.goto_findcblof_model)

        self.pb_FastABOD_model = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_FastABOD_model.setObjectName("pb_FastABOD_model")
        self.gridLayout_3.addWidget(self.pb_FastABOD_model, 1, 1, 1, 1)
        self.pb_FastABOD_model.clicked.connect(self.goto_FastABOD_model)

        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton.clicked.connect(self.goto_EIF)

        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.pushButton_4.clicked.connect(self.goto_LOF)

        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_6.clicked.connect(self.goto_pac_model)

        ########################
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 2, 3, 1, 1)
        self.pushButton_7.clicked.connect(self.goto_pac_model_test)

        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 3, 3, 1, 1)
        self.pushButton_8.clicked.connect(sys.exit)

        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 0, 3, 1, 1)
        self.pushButton_10.clicked.connect(self.goto_LoF_model)

        self.pb_HBOS = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_HBOS.setObjectName("pb_HBOS")
        self.gridLayout_3.addWidget(self.pb_HBOS, 1, 3, 1, 1)
        self.pb_HBOS.clicked.connect(self.goto_hbos_model)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        MainWindowv.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowv)
        QtCore.QMetaObject.connectSlotsByName(MainWindowv)

    def retranslateUi(self, MainWindowv):
        _translate = QtCore.QCoreApplication.translate
        MainWindowv.setWindowTitle(_translate("MainWindowv", "无监督异常学习算法"))
        self.label.setText(_translate("MainWindowv", "基于无监督学习的智能家居异常检测系列算法"))
        self.pushButton_2.setText(_translate("MainWindowv", "FindCBLOF模型训练"))
        self.pushButton_5.setText(_translate("MainWindowv", "HBOS模型训练"))
        self.EIF_Model.setText(_translate("MainWindowv", "EIF模型加载"))
        self.pushButton_3.setText(_translate("MainWindowv", "FastABOD模型训练"))
        self.pb_FindCBLOF_mode.setText(_translate("MainWindowv", "FindCBLOF模型加载"))
        self.pb_FastABOD_model.setText(_translate("MainWindowv", "FastABOD模型加载"))
        self.pushButton.setText(_translate("MainWindowv", "EIF模型训练"))
        self.pushButton_4.setText(_translate("MainWindowv", "LOF模型训练"))
        self.pushButton_6.setText(_translate("MainWindowv", "PCA模型"))
        self.pushButton_7.setText(_translate("MainWindowv", "PCA模型加载"))
        self.pushButton_8.setText(_translate("MainWindowv", "退出"))
        self.pushButton_10.setText(_translate("MainWindowv", "LOF模型加载"))
        self.pb_HBOS.setText(_translate("MainWindowv", "HBOS模型加载"))

    # 训练随机森林模型，对应按钮ID为 pushButton
    def goto_EIF(self):
        self.ui_EIF = QtWidgets.QMainWindow()
        self.eif = Ui_MainWindow_EIF()
        self.eif.setupUi_EIF(self.ui_EIF)
        self.ui_EIF.show()

    # 训练FastABOD模型，对应按钮ID为 pushButton_3
    def goto_FastABOD(self):
        self.ui_FastABOD = QtWidgets.QMainWindow()
        self.FastABOD = Ui_MainWindowv_FastABOD()
        self.FastABOD.setupUi_FastABOD(self.ui_FastABOD)
        self.ui_FastABOD.show()

    # 训练LOF模型，对应的按钮ID为 pushButton_4
    def goto_LOF(self):
        self.ui_LOF = QtWidgets.QMainWindow()
        self.LOF = Ui_MainWindowv_LOF()
        self.LOF.setupUi_LOF(self.ui_LOF)
        self.ui_LOF.show()

    # HBOS模型训练 对应的按钮ID为 pushButton_5
    def goto_HBOS(self):
        self.ui_hbos = QtWidgets.QMainWindow()
        self.hbos = Ui_MainWindowv_Hbos()
        self.hbos.setup_Ui_Hbos(self.ui_hbos)
        self.ui_hbos.show()

    # Find CBLOF模型训练 对应的按钮ID为 pushButton_2
    def goto_FindCBLOF(self):
        self.ui_CBLOF = QtWidgets.QMainWindow()
        self.CBLOF = Ui_MainWindowv_FindCBLOF()
        self.CBLOF.setupUi_FindCBLOF(self.ui_CBLOF)
        self.ui_CBLOF.show()

    # 随机森林模型测试 对应的按钮ID为 EIF_Model
    def goto_EIFmodel_test(self):
        self.ui_model = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_EFmodel()
        self.ui.setupUi_EFmodel(self.ui_model)
        self.ui_model.show()

    # FastABOD模型测试 对应的按钮ID为 pb_FastABOD_model
    def goto_FastABOD_model(self):
        self.uifastabod_model = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_model()
        self.ui.setupUi_model(self.uifastabod_model)
        self.uifastabod_model.show()

    # LOF模型测试 对应的按钮ID为 pushButton_10
    def goto_LoF_model(self):
        self.ui_lof_model = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindowv_LOFmodel()
        self.ui.setupUi_LOFmodel(self.ui_lof_model)
        self.ui_lof_model.show()
        return

    # hbod模型测试 对应的按钮ID为 pb_HBOS
    def goto_hbos_model(self):
        self.uihbos_model = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindowv_test()
        self.ui.setup_Ui_model_hbos(self.uihbos_model)
        self.uihbos_model.show()
        return

    # findcblof 模型测试 对应的按钮ID为 pb_FindCBLOF_mode
    def goto_findcblof_model(self):
        self.uifindcblof_model = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindowv_CBLOF_model()
        self.ui.setupUi_CBLOF_model(self.uifindcblof_model)
        self.uifindcblof_model.show()
        return

    def goto_pac_model(self):
        self.MainWindowv = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindowv_PCA()
        self.ui.setup_Ui_PCA(self.MainWindowv)
        self.MainWindowv.show()

    def goto_pac_model_test(self):
        self.MainWindowv = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindowv_PCAmodel()
        self.ui.setupUi_PCAmodel(self.MainWindowv)
        self.MainWindowv.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowv = QtWidgets.QMainWindow()
    ui = Ui_MainWindowv()
    ui.setupUi(MainWindowv)
    MainWindowv.show()
    sys.exit(app.exec_())
