# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QEventLoop, QTimer
from PyQt5.QtGui import QTextCursor, QPixmap
from PyQt5.QtWidgets import QFileDialog
import sys
import os
sys.path.append('../model')

from abod.FastABODModel_Test import Ui_MainWindow_model
from abod import abod_test


class EmittingStr(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str)  # 定义一个发送str的信号

    def write(self, text):
        self.textWritten.emit(str(text))


class Ui_MainWindowv_FastABOD(object):

    def __init__(self):
        super(Ui_MainWindowv_FastABOD).__init__()
        # self.datasize = 0.2
        # self.recent_point = 20
        # self.Abnormal_proportion = 0.12
        self.filePath = None
        sys.stdout = EmittingStr(textWritten=self.updatetext)
        sys.stderr = EmittingStr(textWritten=self.updatetext)
        self.cwd = os.path.dirname(os.path.dirname(__file__))

    def setupUi_FastABOD(self, MainWindowv):
        MainWindowv.setObjectName("MainWindowv")
        MainWindowv.setEnabled(True)
        MainWindowv.resize(1200, 800)
        MainWindowv.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        MainWindowv.setFont(font)
        MainWindowv.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindowv.setAutoFillBackground(False)
        MainWindowv.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                  "color: rgb(13, 13, 13);")
        MainWindowv.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindowv)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(16, 16, 16);")
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(211, 255, 224);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 387))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_info_show = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_info_show.setFont(font)
        self.tabWidget_info_show.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_info_show.setStyleSheet("background-color: rgb(124, 221, 215);\n"
                                               "font: 12pt \"Times New Roman\";")
        self.tabWidget_info_show.setObjectName("tabWidget_info_show")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.load_model = QtWidgets.QPushButton(self.tab_7)
        self.load_model.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.load_model.setObjectName("load_model")
        self.gridLayout_6.addWidget(self.load_model, 0, 1, 1, 1)

        # self.load_class_path = QtWidgets.QLineEdit(self.tab_7)
        # self.load_class_path.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.load_class_path.setObjectName("load_class_path")
        # self.gridLayout_6.addWidget(self.load_class_path, 1, 3, 1, 1)
        self.load_class = QtWidgets.QPushButton(self.tab_7)
        self.load_class.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.load_class.setObjectName("load_class")
        self.gridLayout_6.addWidget(self.load_class, 1, 3, 1, 1)
        # self.gridLayout_6.addWidget(self.load_class, 1, 1, 1, 1)
        self.load_class.clicked.connect(self.goto_model)

        self.load_model_path = QtWidgets.QLineEdit(self.tab_7)
        self.load_model_path.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.load_model_path.setObjectName("load_model_path")
        self.gridLayout_6.addWidget(self.load_model_path, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 4, 5, 1, 1)

        self.Text_Browser = QtWidgets.QTextBrowser(self.tab_7)
        self.Text_Browser.setMinimumSize(QtCore.QSize(16777215, 16777215))
        self.Text_Browser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Text_Browser.setText("")
        self.Text_Browser.setObjectName("Text_Browser")
        self.gridLayout_5.addWidget(self.Text_Browser, 2, 5, 2, 1)
        # self.label_img_show = QtWidgets.QLabel(self.tab_7)
        # self.label_img_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # self.label_img_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.label_img_show.setText("")
        # self.label_img_show.setObjectName("label_img_show")
        # self.gridLayout_5.addWidget(self.label_img_show, 2, 5, 2, 1)
        self.tabWidget_info_show.addTab(self.tab_7, "")
        self.gridLayout_3.addWidget(self.tabWidget_info_show, 2, 1, 1, 1)
        self.tabWidget_oper = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_oper.setFont(font)
        self.tabWidget_oper.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_oper.setStyleSheet("background-color: rgb(124, 221, 215);\n"
                                          "font: 12pt \"Times New Roman\";")
        self.tabWidget_oper.setObjectName("tabWidget_oper")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.load_xml_path = QtWidgets.QPushButton(self.tab_6)
        self.load_xml_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.load_xml_path.setObjectName("load_xml_path")
        self.gridLayout.addWidget(self.load_xml_path, 1, 0, 1, 1)

        self.lineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 4, 1, 1)
        self.lineEdit.setText(str(20))  # 最近点数

        self.pb_run = QtWidgets.QPushButton(self.tab_6)
        self.pb_run.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.pb_run.setObjectName("pb_run")
        self.gridLayout.addWidget(self.pb_run, 3, 1, 1, 1)
        self.pb_run.clicked.connect(self.run_function_abod)

        self.label_epoch = QtWidgets.QPushButton(self.tab_6)
        self.label_epoch.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.label_epoch.setObjectName("label_epoch")
        self.gridLayout.addWidget(self.label_epoch, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.pushButton_2.clicked.connect(self.getFilePath)

        self.le_save_dir_path = QtWidgets.QLineEdit(self.tab_6)
        self.le_save_dir_path.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.le_save_dir_path.setObjectName("le_save_dir_path")
        self.gridLayout.addWidget(self.le_save_dir_path, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 4, 1, 1)
        self.lineEdit_2.setText(str(0.12))  # 异常占比

        self.load_train_path = QtWidgets.QPushButton(self.tab_6)
        self.load_train_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.load_train_path.setObjectName("load_train_path")
        self.gridLayout.addWidget(self.load_train_path, 0, 0, 1, 1)
        self.pb_quit = QtWidgets.QPushButton(self.tab_6)
        self.pb_quit.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.pb_quit.setObjectName("pb_quit")
        self.gridLayout.addWidget(self.pb_quit, 3, 2, 1, 1)
        self.pb_quit.clicked.connect(MainWindowv.close)

        self.pushButton = QtWidgets.QPushButton(self.tab_6)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton.clicked.connect(self.getFileName)

        self.load_train_pic_path = QtWidgets.QLineEdit(self.tab_6)
        self.load_train_pic_path.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.load_train_pic_path.setObjectName("load_train_pic_path")
        self.gridLayout.addWidget(self.load_train_pic_path, 0, 1, 1, 1)
        self.pb_save_dir_path = QtWidgets.QPushButton(self.tab_6)
        self.pb_save_dir_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.pb_save_dir_path.setObjectName("pb_save_dir_path")
        self.gridLayout.addWidget(self.pb_save_dir_path, 2, 0, 1, 1)
        self.load_xml_path_2 = QtWidgets.QLineEdit(self.tab_6)
        self.load_xml_path_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.load_xml_path_2.setObjectName("load_xml_path_2")
        self.gridLayout.addWidget(self.load_xml_path_2, 1, 1, 1, 1)
        self.load_xml_path_2.setText(str(0.2))

        self.label_batch = QtWidgets.QPushButton(self.tab_6)
        self.label_batch.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.label_batch.setObjectName("label_batch")
        self.gridLayout.addWidget(self.label_batch, 1, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 1)

        # self.textBrowser = QtWidgets.QTextBrowser(self.tab_6)
        # self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.textBrowser.setObjectName("textBrowser")
        # self.gridLayout_4.addWidget(self.textBrowser, 3, 0, 1, 1)

        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        # self.textBrowser = QtWidgets.QTextBrowser(self.tab_6)
        # self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.textBrowser.setObjectName("textBrowser")
        # self.gridLayout_9.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QLabel(self.tab_6)
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_9.addWidget(self.textBrowser_2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        self.tabWidget_oper.addTab(self.tab_6, "")
        self.gridLayout_3.addWidget(self.tabWidget_oper, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.tabWidget_oper.addTab(self.tab_6, "")
        self.gridLayout_3.addWidget(self.tabWidget_oper, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        MainWindowv.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowv)
        self.tabWidget_info_show.setCurrentIndex(0)
        self.tabWidget_oper.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowv)

    def retranslateUi(self, MainWindowv):
        _translate = QtCore.QCoreApplication.translate
        MainWindowv.setWindowTitle(_translate("MainWindowv", "无监督异常学习算法"))
        self.label.setText(_translate("MainWindowv", "FastABOD模型训练"))
        self.load_model.setText(_translate("MainWindowv", "模型路径"))
        self.load_class.setText(_translate("MainWindowv", "加载模型"))
        self.tabWidget_info_show.setTabText(self.tabWidget_info_show.indexOf(self.tab_7),
                                            _translate("MainWindowv", "执行显示"))
        self.load_xml_path.setText(_translate("MainWindowv", "数据集大小"))
        self.pb_run.setText(_translate("MainWindowv", "训练"))
        self.label_epoch.setText(_translate("MainWindowv", "最近点数"))
        self.pushButton_2.setText(_translate("MainWindowv", "选择路径"))
        self.load_train_path.setText(_translate("MainWindowv", "数据集选取"))
        self.pb_quit.setText(_translate("MainWindowv", "退出"))
        self.pushButton.setText(_translate("MainWindowv", "选择文件"))
        self.pb_save_dir_path.setText(_translate("MainWindowv", "模型保存路径"))
        self.label_batch.setText(_translate("MainWindowv", "异常占比"))
        self.tabWidget_oper.setTabText(self.tabWidget_oper.indexOf(self.tab_6), _translate("MainWindowv", "操作窗口"))

    def goto_model(self):
        self.model = QtWidgets.QMainWindow()
        self.ui_model = Ui_MainWindow_model()
        self.ui_model.setupUi_model(self.model)
        self.model.show()

    def updatetext(self, text):
        """
            更新textBrowser
        """
        cursor = self.Text_Browser.textCursor()
        cursor.movePosition(QTextCursor.End)
        self.Text_Browser.append(text)
        self.Text_Browser.setTextCursor(cursor)
        self.Text_Browser.ensureCursorVisible()
        QtWidgets.QApplication.processEvents()

    def genMastClicked(self):
        """Runs the main function."""
        # print(self.fileName)
        # print(self.filePath)
        loop = QEventLoop()
        QTimer.singleShot(1000, loop.quit)
        loop.exec_()
        print('Done.')

    def getFileName(self):  # 选取训练文件地址
        fileName, _ = QFileDialog.getOpenFileName(None, 'Single File', self.cwd, "*.csv")
        self.load_train_pic_path.setText(fileName)
        self.fileName = self.load_train_pic_path.text()
        # f = open(fileName,'r')
        # with f:
        #     data = f.read()
        #     self.textEdit_1.setText(data)

    def getFilePath(self):  # 选取模型保存的路径
        filePath = QFileDialog.getExistingDirectory(None, "选取文件夹", self.cwd)
        self.le_save_dir_path.setText(filePath)
        self.filePath = self.le_save_dir_path.text()
        self.load_model_path.setText(self.filePath)
        # print("3")

    def run_function_abod(self):
        print("----------BEGIN-----------")
        if self.fileName != "":
            recent_point = int(self.lineEdit.text())
            Abnormal_proportion = float(self.lineEdit_2.text())
            Frace = float(self.load_xml_path_2.text())
            raw_data_filename2 = self.le_save_dir_path.text()
            # print(recent_point)
            # print(Abnormal_proportion)
            # print(Frace)
            # print(raw_data_filename2)
            # print(self.load_train_pic_path.text())
            abod_test.abod_run(raw_data_filename1=self.load_train_pic_path.text(),
                               raw_data_filename2=raw_data_filename2,
                               Frace=Frace, recent_point=recent_point,
                               Abnormal_proportion=Abnormal_proportion)
            self.image1()
            self.genMastClicked()

    def image1(self):
        pixmap = QPixmap(self.cwd + "/image/fastabod.png")
        self.textBrowser_2.setPixmap(pixmap)
        self.textBrowser_2.setScaledContents(True)
        self.textBrowser_2.repaint()
        return


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindowv = QtWidgets.QMainWindow()
    ui = Ui_MainWindowv_FastABOD()
    ui.setupUi_FastABOD(MainWindowv)
    MainWindowv.show()
    sys.exit(app.exec_())
